#!/bin/bash

help() {
  echo "Fuzzy Git File Adder - based on fzf"
  echo ""
  echo "Usage: git fza <path>"
}

command -v fzf >/dev/null 2>&1 || { echo >&2 "fzf is required but not installed (https://github.com/junegunn/fzf)"; exit 1; }

if [ "$#" -ne 1 ]; then
    help
fi

# TODO: Restrict files to already tracked files?
files=$(git status --porcelain | awk '{print $2}')
matches=$(echo "$files" | fzf --no-sort -f "$1")

if [[ $(echo "$matches" | wc -l) -ne 1 ]]; then
  echo "The following files matched the pattern:"
  echo ""
  echo "$matches"
  echo ""
  # TODO: Support adding of all matching files, with a switch? (-a | --all)
  echo "Adding of only a single file match is supported."
  exit
fi

# All done!
git add $matches