#!/bin/bash

help() {
  echo "Fuzzy Git File Adder - based on fzf"
  echo ""
  echo "Usage: git fza <path>"
  exit 1
}

command -v fzf >/dev/null 2>&1 || { echo >&2 "fzf is required but not installed (https://github.com/junegunn/fzf)"; exit 1; }

if [ "$#" -ne 1 ]; then
    help
fi

# TODO: Restrict files to already tracked files?
# TODO: Support adding of all matching files, with a switch? (-a | --all)
matches=$(git status --porcelain | awk '{print $2}' | fzf --no-sort -1 -q "$1")

# All done!
git add $matches
