#!/usr/bin/env python3

import subprocess

import click
import requests

from lxml.html import fromstring


def fetch_title(url):
    r = requests.get(url)
    tree = fromstring(r.content)
    return tree.findtext('.//title')


def cmd_cutycapt(url, title):
    return [
        "cutycapt",
        "--url=%s" % url,
        "--out=%s.pdf" % title,
    ]


def cmd_wkhtmltopdf(url, title):
    return [
        "wkhtmltopdf",
        "--margin-top", "0",
        "--margin-bottom", "0",
        "--margin-left", "0",
        "--margin-right", "0",
        "--no-background",
        url,
        "%s.pdf" % title,
    ]



    cmd = cmd_wkhtmltopdf(url, title)

    if cutycapt:
        cmd = cmd_cutycapt(url, title)

    print(" ".join(cmd))
    subprocess.call(cmd)


@click.command()
@click.option('--wkhtmltopdf', '-w', is_flag=True)
@click.option('--cutycapt', '-c', is_flag=True)
@click.argument('url', required=False)
@click.option('--file', '-f', type=click.File('r'))
def cli(url, file, **kwargs):

    if url:
        convert_url(url, **kwargs)

    elif file:
        for line in file.readlines():
            line = line.strip()
            if line and not line.startswith("#"):
                convert_url(line, **kwargs)

if __name__ == '__main__':
    cli()
