#!/usr/bin/python
"""
rotor - minimalistic rtorrent client

Usage:
    rotor ls
    rotor add <torrent>
    rotor add -i <file>
"""

import sys
import xmlrpclib

import docopt

SERVER_URL = ""


def ls(r):
    # Get torrents in the main view
    mainview = r.download_list("", "main")

    for torrent in mainview:
        print(r.d.get_name(torrent))


if __name__ == '__main__':
    args = docopt.docopt(__doc__)

    r = xmlrpclib.Server(SERVER_URL)

    if args['add']:
        if args['-i']:
            if args['<file>'] == '-':
                file = sys.stdin
            else:
                file = open(args['<file>'])

            # TODO: Is reading all lines at once necessary?
            for torrent in file.readlines():
                if torrent.strip():
                    r.load(torrent.strip())

            file.close()
        else:
            r.load_start(args['<torrent>'])
    elif args['ls']:
        ls(r)
