#!/usr/bin/env python3

"""
Get MP3 links from a songspk album URL.

Usage:
    songspk <url>
    songspk -i <file>

Examples:
    songspk http://songsbling.com/indian-movies-songs/ishq-positive.html

    songspk -i urls.txt
"""

import sys
import urllib.parse

from multiprocessing.pool import ThreadPool

import docopt
import pyquery


def url_fix(url):
    scheme, netloc, path, qs, anchor = urllib.parse.urlsplit(url)
    path = urllib.parse.quote(path, '/%')
    qs = urllib.parse.quote_plus(qs, ':&=')
    return urllib.parse.urlunsplit((scheme, netloc, path, qs, anchor))


def get_links_from_page(page_url):
    pq = pyquery.PyQuery(url=page_url)
    return [url_fix(a.get('href')) for a in pq('div.download-trget a')]


def get_links_from_albums_page(album_url):
    urls = [
        url for url in get_links_from_page(album_url)
        if '/downloads/' in url
    ]

    pool = ThreadPool(processes=5)
    for results in pool.imap_unordered(get_links_from_page, urls):
        print("\n".join(url for url in results if "index.php?id=" in url))


if __name__ == '__main__':
    args = docopt.docopt(__doc__)

    url = args['<url>']
    file = args['<file>']

    if url:
        if "/downloads/" in url:
            print(get_links_from_page(url))
        else:
            get_links_from_albums_page(url)
    elif args['-i']:
        if file == '-':
            file = sys.stdin
        else:
            file = open(file)

        # TODO: Is reading all lines at once necessary?
        for url in file.readlines():
            if url.strip():
                get_links_from_albums_page(url.strip())

        file.close()
