#!/usr/bin/env python3

"""
torrentz - extract torrent links from a webpage.

Usage:
    torrentz https://yts.ag/*
    torrentz https://www.shaanig.org/*
"""

import sys

import pyquery


def get_torrent_links(source):
    """ Print all URLs that begin with 'magnet' or end with '.torrent' """

    pq = pyquery.PyQuery(url=source)

    # Prevents duplicate links
    seen = set()

    for a in pq.find('a'):
        href = a.get('href')

        if href and (href.startswith("magnet") or
                     href.endswith(".torrent") and
                     href not in seen and
                     "1080p" not in a.get('title', '')):

            print("%s %s" % (a.get('title', ''), href))
            print()

            seen.add(href)


if __name__ == '__main__':
    get_torrent_links(sys.argv[1])
